// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: articles.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countUnreadArticles = `-- name: CountUnreadArticles :one
SELECT COUNT(*)
FROM articles a
JOIN feeds f ON f.id = a.feed_id
WHERE f.user_id = ? AND a.is_read = 0
`

func (q *Queries) CountUnreadArticles(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadArticles, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one
INSERT OR IGNORE INTO articles (
    feed_id, guid, url, title, author, content, excerpt, published_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, feed_id, guid, url, title, author, content, excerpt, published_at,
          created_at, is_read, is_starred
`

type CreateArticleParams struct {
	FeedID      int64          `json:"feed_id"`
	Guid        string         `json:"guid"`
	Url         string         `json:"url"`
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	Content     sql.NullString `json:"content"`
	Excerpt     sql.NullString `json:"excerpt"`
	PublishedAt sql.NullTime   `json:"published_at"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.FeedID,
		arg.Guid,
		arg.Url,
		arg.Title,
		arg.Author,
		arg.Content,
		arg.Excerpt,
		arg.PublishedAt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Guid,
		&i.Url,
		&i.Title,
		&i.Author,
		&i.Content,
		&i.Excerpt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.IsRead,
		&i.IsStarred,
	)
	return i, err
}

const listArticlesByFeed = `-- name: ListArticlesByFeed :many
SELECT id, feed_id, guid, url, title, author, content, excerpt, published_at,
       created_at, is_read, is_starred
FROM articles
WHERE feed_id = ?
ORDER BY published_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListArticlesByFeedParams struct {
	FeedID int64 `json:"feed_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListArticlesByFeed(ctx context.Context, arg ListArticlesByFeedParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesByFeed, arg.FeedID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Url,
			&i.Title,
			&i.Author,
			&i.Content,
			&i.Excerpt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.IsRead,
			&i.IsStarred,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentArticles = `-- name: ListRecentArticles :many
SELECT
    a.id,
    a.feed_id,
    a.guid,
    a.url,
    a.title,
    a.author,
    a.content,
    a.excerpt,
    a.published_at,
    a.created_at,
    a.is_read,
    a.is_starred,
    f.title AS feed_title,
    COALESCE(c.name, 'Uncategorized') AS category
FROM articles a
JOIN feeds f ON f.id = a.feed_id
LEFT JOIN categories c ON c.id = f.category_id
WHERE f.user_id = ?
ORDER BY COALESCE(a.published_at, a.created_at) DESC, a.id DESC
LIMIT ? OFFSET ?
`

type ListRecentArticlesParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListRecentArticlesRow struct {
	ID          int64          `json:"id"`
	FeedID      int64          `json:"feed_id"`
	Guid        string         `json:"guid"`
	Url         string         `json:"url"`
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	Content     sql.NullString `json:"content"`
	Excerpt     sql.NullString `json:"excerpt"`
	PublishedAt sql.NullTime   `json:"published_at"`
	CreatedAt   time.Time      `json:"created_at"`
	IsRead      int64          `json:"is_read"`
	IsStarred   int64          `json:"is_starred"`
	FeedTitle   string         `json:"feed_title"`
	Category    string         `json:"category"`
}

func (q *Queries) ListRecentArticles(ctx context.Context, arg ListRecentArticlesParams) ([]ListRecentArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentArticles, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentArticlesRow
	for rows.Next() {
		var i ListRecentArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Url,
			&i.Title,
			&i.Author,
			&i.Content,
			&i.Excerpt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedTitle,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArticleRead = `-- name: MarkArticleRead :exec
UPDATE articles
SET is_read = ?
WHERE id = ?
`

type MarkArticleReadParams struct {
	IsRead int64 `json:"is_read"`
	ID     int64 `json:"id"`
}

func (q *Queries) MarkArticleRead(ctx context.Context, arg MarkArticleReadParams) error {
	_, err := q.db.ExecContext(ctx, markArticleRead, arg.IsRead, arg.ID)
	return err
}

const searchArticles = `-- name: SearchArticles :many
SELECT
    a.id,
    a.feed_id,
    a.url,
    a.title,
    a.excerpt,
    a.published_at,
    f.title AS feed_title,
    a.title AS title_snippet,
    COALESCE(a.excerpt, '') AS content_snippet
FROM articles a
JOIN feeds f ON f.id = a.feed_id
WHERE f.user_id = ?
  AND (
    a.title LIKE '%' || ? || '%'
    OR a.content LIKE '%' || ? || '%'
    OR a.author LIKE '%' || ? || '%'
  )
ORDER BY a.published_at DESC, a.id DESC
LIMIT 50
`

type SearchArticlesParams struct {
	UserID  int64          `json:"user_id"`
	Column2 sql.NullString `json:"column_2"`
	Column3 sql.NullString `json:"column_3"`
	Column4 sql.NullString `json:"column_4"`
}

type SearchArticlesRow struct {
	ID             int64          `json:"id"`
	FeedID         int64          `json:"feed_id"`
	Url            string         `json:"url"`
	Title          string         `json:"title"`
	Excerpt        sql.NullString `json:"excerpt"`
	PublishedAt    sql.NullTime   `json:"published_at"`
	FeedTitle      string         `json:"feed_title"`
	TitleSnippet   string         `json:"title_snippet"`
	ContentSnippet string         `json:"content_snippet"`
}

func (q *Queries) SearchArticles(ctx context.Context, arg SearchArticlesParams) ([]SearchArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchArticles,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchArticlesRow
	for rows.Next() {
		var i SearchArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Url,
			&i.Title,
			&i.Excerpt,
			&i.PublishedAt,
			&i.FeedTitle,
			&i.TitleSnippet,
			&i.ContentSnippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const starArticle = `-- name: StarArticle :exec
UPDATE articles
SET is_starred = ?
WHERE id = ?
`

type StarArticleParams struct {
	IsStarred int64 `json:"is_starred"`
	ID        int64 `json:"id"`
}

func (q *Queries) StarArticle(ctx context.Context, arg StarArticleParams) error {
	_, err := q.db.ExecContext(ctx, starArticle, arg.IsStarred, arg.ID)
	return err
}
