// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: articles.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countAllArticles = `-- name: CountAllArticles :one
SELECT COUNT(*)
FROM articles a
JOIN feeds f ON f.id = a.feed_id
WHERE f.user_id = ?
`

func (q *Queries) CountAllArticles(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllArticles, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReadLaterArticles = `-- name: CountReadLaterArticles :one
SELECT COUNT(*)
FROM articles a
JOIN feeds f ON f.id = a.feed_id
WHERE f.user_id = ? AND a.is_read_later = 1
`

func (q *Queries) CountReadLaterArticles(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReadLaterArticles, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStarredArticles = `-- name: CountStarredArticles :one
SELECT COUNT(*)
FROM articles a
JOIN feeds f ON f.id = a.feed_id
WHERE f.user_id = ? AND a.is_starred = 1
`

func (q *Queries) CountStarredArticles(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStarredArticles, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadArticles = `-- name: CountUnreadArticles :one
SELECT COUNT(*)
FROM articles a
JOIN feeds f ON f.id = a.feed_id
WHERE f.user_id = ? AND a.is_read = 0
`

func (q *Queries) CountUnreadArticles(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadArticles, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadArticlesByCategory = `-- name: CountUnreadArticlesByCategory :many
SELECT f.category_id, COUNT(a.id) AS unread_count
FROM articles a
JOIN feeds f ON f.id = a.feed_id
WHERE f.user_id = ? AND a.is_read = 0
GROUP BY f.category_id
`

type CountUnreadArticlesByCategoryRow struct {
	CategoryID  sql.NullInt64 `json:"category_id"`
	UnreadCount int64         `json:"unread_count"`
}

func (q *Queries) CountUnreadArticlesByCategory(ctx context.Context, userID int64) ([]CountUnreadArticlesByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, countUnreadArticlesByCategory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountUnreadArticlesByCategoryRow
	for rows.Next() {
		var i CountUnreadArticlesByCategoryRow
		if err := rows.Scan(&i.CategoryID, &i.UnreadCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnreadArticlesByFeed = `-- name: CountUnreadArticlesByFeed :many
SELECT feed_id, COUNT(*) AS unread_count
FROM articles
WHERE is_read = 0
  AND feed_id IN (SELECT id FROM feeds WHERE user_id = ?)
GROUP BY feed_id
`

type CountUnreadArticlesByFeedRow struct {
	FeedID      int64 `json:"feed_id"`
	UnreadCount int64 `json:"unread_count"`
}

func (q *Queries) CountUnreadArticlesByFeed(ctx context.Context, userID int64) ([]CountUnreadArticlesByFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, countUnreadArticlesByFeed, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountUnreadArticlesByFeedRow
	for rows.Next() {
		var i CountUnreadArticlesByFeedRow
		if err := rows.Scan(&i.FeedID, &i.UnreadCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createArticle = `-- name: CreateArticle :one
INSERT OR IGNORE INTO articles (
    feed_id, guid, url, title, author, content, excerpt, image_url, published_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, feed_id, guid, url, title, author, content, excerpt, image_url, published_at,
          created_at, is_read, is_starred, is_read_later
`

type CreateArticleParams struct {
	FeedID      int64          `json:"feed_id"`
	Guid        string         `json:"guid"`
	Url         string         `json:"url"`
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	Content     sql.NullString `json:"content"`
	Excerpt     sql.NullString `json:"excerpt"`
	ImageUrl    sql.NullString `json:"image_url"`
	PublishedAt sql.NullTime   `json:"published_at"`
}

type CreateArticleRow struct {
	ID          int64          `json:"id"`
	FeedID      int64          `json:"feed_id"`
	Guid        string         `json:"guid"`
	Url         string         `json:"url"`
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	Content     sql.NullString `json:"content"`
	Excerpt     sql.NullString `json:"excerpt"`
	ImageUrl    sql.NullString `json:"image_url"`
	PublishedAt sql.NullTime   `json:"published_at"`
	CreatedAt   time.Time      `json:"created_at"`
	IsRead      int64          `json:"is_read"`
	IsStarred   int64          `json:"is_starred"`
	IsReadLater int64          `json:"is_read_later"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (CreateArticleRow, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.FeedID,
		arg.Guid,
		arg.Url,
		arg.Title,
		arg.Author,
		arg.Content,
		arg.Excerpt,
		arg.ImageUrl,
		arg.PublishedAt,
	)
	var i CreateArticleRow
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Guid,
		&i.Url,
		&i.Title,
		&i.Author,
		&i.Content,
		&i.Excerpt,
		&i.ImageUrl,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.IsRead,
		&i.IsStarred,
		&i.IsReadLater,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles
WHERE articles.id = ?
  AND articles.feed_id IN (SELECT feeds.id FROM feeds WHERE feeds.user_id = ?)
`

type DeleteArticleParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteArticle(ctx context.Context, arg DeleteArticleParams) error {
	_, err := q.db.ExecContext(ctx, deleteArticle, arg.ID, arg.UserID)
	return err
}

const deleteReadArticlesOlderThan = `-- name: DeleteReadArticlesOlderThan :exec
DELETE FROM articles
WHERE is_read = 1
  AND created_at < datetime('now', printf('-%d days', ?))
  AND feed_id IN (SELECT id FROM feeds WHERE user_id = ?)
`

type DeleteReadArticlesOlderThanParams struct {
	PRINTF interface{} `json:"PRINTF"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) DeleteReadArticlesOlderThan(ctx context.Context, arg DeleteReadArticlesOlderThanParams) error {
	_, err := q.db.ExecContext(ctx, deleteReadArticlesOlderThan, arg.PRINTF, arg.UserID)
	return err
}

const listArticlesByFeed = `-- name: ListArticlesByFeed :many
SELECT id, feed_id, guid, url, title, author, content, excerpt, image_url, published_at,
       created_at, is_read, is_starred, is_read_later
FROM articles
WHERE feed_id = ?
ORDER BY published_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListArticlesByFeedParams struct {
	FeedID int64 `json:"feed_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListArticlesByFeedRow struct {
	ID          int64          `json:"id"`
	FeedID      int64          `json:"feed_id"`
	Guid        string         `json:"guid"`
	Url         string         `json:"url"`
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	Content     sql.NullString `json:"content"`
	Excerpt     sql.NullString `json:"excerpt"`
	ImageUrl    sql.NullString `json:"image_url"`
	PublishedAt sql.NullTime   `json:"published_at"`
	CreatedAt   time.Time      `json:"created_at"`
	IsRead      int64          `json:"is_read"`
	IsStarred   int64          `json:"is_starred"`
	IsReadLater int64          `json:"is_read_later"`
}

func (q *Queries) ListArticlesByFeed(ctx context.Context, arg ListArticlesByFeedParams) ([]ListArticlesByFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesByFeed, arg.FeedID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticlesByFeedRow
	for rows.Next() {
		var i ListArticlesByFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Url,
			&i.Title,
			&i.Author,
			&i.Content,
			&i.Excerpt,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.IsReadLater,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadLaterArticles = `-- name: ListReadLaterArticles :many
SELECT
    a.id,
    a.feed_id,
    a.guid,
    a.url,
    a.title,
    a.author,
    a.content,
    a.excerpt,
    a.image_url,
    a.published_at,
    a.created_at,
    a.is_read,
    a.is_starred,
    a.is_read_later,
    f.title AS feed_title,
    COALESCE(c.name, 'Uncategorized') AS category
FROM articles a
JOIN feeds f ON f.id = a.feed_id
LEFT JOIN categories c ON c.id = f.category_id
WHERE f.user_id = ? AND a.is_read_later = 1
ORDER BY COALESCE(a.published_at, a.created_at) DESC, a.id DESC
LIMIT ? OFFSET ?
`

type ListReadLaterArticlesParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListReadLaterArticlesRow struct {
	ID          int64          `json:"id"`
	FeedID      int64          `json:"feed_id"`
	Guid        string         `json:"guid"`
	Url         string         `json:"url"`
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	Content     sql.NullString `json:"content"`
	Excerpt     sql.NullString `json:"excerpt"`
	ImageUrl    sql.NullString `json:"image_url"`
	PublishedAt sql.NullTime   `json:"published_at"`
	CreatedAt   time.Time      `json:"created_at"`
	IsRead      int64          `json:"is_read"`
	IsStarred   int64          `json:"is_starred"`
	IsReadLater int64          `json:"is_read_later"`
	FeedTitle   string         `json:"feed_title"`
	Category    string         `json:"category"`
}

func (q *Queries) ListReadLaterArticles(ctx context.Context, arg ListReadLaterArticlesParams) ([]ListReadLaterArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listReadLaterArticles, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReadLaterArticlesRow
	for rows.Next() {
		var i ListReadLaterArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Url,
			&i.Title,
			&i.Author,
			&i.Content,
			&i.Excerpt,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.IsReadLater,
			&i.FeedTitle,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentArticles = `-- name: ListRecentArticles :many
SELECT
    a.id,
    a.feed_id,
    a.guid,
    a.url,
    a.title,
    a.author,
    a.content,
    a.excerpt,
    a.image_url,
    a.published_at,
    a.created_at,
    a.is_read,
    a.is_starred,
    a.is_read_later,
    f.title AS feed_title,
    COALESCE(c.name, 'Uncategorized') AS category
FROM articles a
JOIN feeds f ON f.id = a.feed_id
LEFT JOIN categories c ON c.id = f.category_id
WHERE f.user_id = ?
ORDER BY COALESCE(a.published_at, a.created_at) DESC, a.id DESC
LIMIT ? OFFSET ?
`

type ListRecentArticlesParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListRecentArticlesRow struct {
	ID          int64          `json:"id"`
	FeedID      int64          `json:"feed_id"`
	Guid        string         `json:"guid"`
	Url         string         `json:"url"`
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	Content     sql.NullString `json:"content"`
	Excerpt     sql.NullString `json:"excerpt"`
	ImageUrl    sql.NullString `json:"image_url"`
	PublishedAt sql.NullTime   `json:"published_at"`
	CreatedAt   time.Time      `json:"created_at"`
	IsRead      int64          `json:"is_read"`
	IsStarred   int64          `json:"is_starred"`
	IsReadLater int64          `json:"is_read_later"`
	FeedTitle   string         `json:"feed_title"`
	Category    string         `json:"category"`
}

func (q *Queries) ListRecentArticles(ctx context.Context, arg ListRecentArticlesParams) ([]ListRecentArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentArticles, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentArticlesRow
	for rows.Next() {
		var i ListRecentArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Url,
			&i.Title,
			&i.Author,
			&i.Content,
			&i.Excerpt,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.IsReadLater,
			&i.FeedTitle,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentArticlesByCategory = `-- name: ListRecentArticlesByCategory :many
SELECT
    a.id,
    a.feed_id,
    a.guid,
    a.url,
    a.title,
    a.author,
    a.content,
    a.excerpt,
    a.image_url,
    a.published_at,
    a.created_at,
    a.is_read,
    a.is_starred,
    a.is_read_later,
    f.title AS feed_title,
    COALESCE(c.name, 'Uncategorized') AS category
FROM articles a
JOIN feeds f ON f.id = a.feed_id
LEFT JOIN categories c ON c.id = f.category_id
WHERE f.user_id = ? AND f.category_id = ?
ORDER BY COALESCE(a.published_at, a.created_at) DESC, a.id DESC
LIMIT ? OFFSET ?
`

type ListRecentArticlesByCategoryParams struct {
	UserID     int64         `json:"user_id"`
	CategoryID sql.NullInt64 `json:"category_id"`
	Limit      int64         `json:"limit"`
	Offset     int64         `json:"offset"`
}

type ListRecentArticlesByCategoryRow struct {
	ID          int64          `json:"id"`
	FeedID      int64          `json:"feed_id"`
	Guid        string         `json:"guid"`
	Url         string         `json:"url"`
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	Content     sql.NullString `json:"content"`
	Excerpt     sql.NullString `json:"excerpt"`
	ImageUrl    sql.NullString `json:"image_url"`
	PublishedAt sql.NullTime   `json:"published_at"`
	CreatedAt   time.Time      `json:"created_at"`
	IsRead      int64          `json:"is_read"`
	IsStarred   int64          `json:"is_starred"`
	IsReadLater int64          `json:"is_read_later"`
	FeedTitle   string         `json:"feed_title"`
	Category    string         `json:"category"`
}

func (q *Queries) ListRecentArticlesByCategory(ctx context.Context, arg ListRecentArticlesByCategoryParams) ([]ListRecentArticlesByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentArticlesByCategory,
		arg.UserID,
		arg.CategoryID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentArticlesByCategoryRow
	for rows.Next() {
		var i ListRecentArticlesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Url,
			&i.Title,
			&i.Author,
			&i.Content,
			&i.Excerpt,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.IsReadLater,
			&i.FeedTitle,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentArticlesByFeed = `-- name: ListRecentArticlesByFeed :many
SELECT
    a.id,
    a.feed_id,
    a.guid,
    a.url,
    a.title,
    a.author,
    a.content,
    a.excerpt,
    a.image_url,
    a.published_at,
    a.created_at,
    a.is_read,
    a.is_starred,
    a.is_read_later,
    f.title AS feed_title,
    COALESCE(c.name, 'Uncategorized') AS category
FROM articles a
JOIN feeds f ON f.id = a.feed_id
LEFT JOIN categories c ON c.id = f.category_id
WHERE f.user_id = ? AND f.id = ?
ORDER BY COALESCE(a.published_at, a.created_at) DESC, a.id DESC
LIMIT ? OFFSET ?
`

type ListRecentArticlesByFeedParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListRecentArticlesByFeedRow struct {
	ID          int64          `json:"id"`
	FeedID      int64          `json:"feed_id"`
	Guid        string         `json:"guid"`
	Url         string         `json:"url"`
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	Content     sql.NullString `json:"content"`
	Excerpt     sql.NullString `json:"excerpt"`
	ImageUrl    sql.NullString `json:"image_url"`
	PublishedAt sql.NullTime   `json:"published_at"`
	CreatedAt   time.Time      `json:"created_at"`
	IsRead      int64          `json:"is_read"`
	IsStarred   int64          `json:"is_starred"`
	IsReadLater int64          `json:"is_read_later"`
	FeedTitle   string         `json:"feed_title"`
	Category    string         `json:"category"`
}

func (q *Queries) ListRecentArticlesByFeed(ctx context.Context, arg ListRecentArticlesByFeedParams) ([]ListRecentArticlesByFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentArticlesByFeed,
		arg.UserID,
		arg.ID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentArticlesByFeedRow
	for rows.Next() {
		var i ListRecentArticlesByFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Url,
			&i.Title,
			&i.Author,
			&i.Content,
			&i.Excerpt,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.IsReadLater,
			&i.FeedTitle,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStarredArticles = `-- name: ListStarredArticles :many
SELECT
    a.id,
    a.feed_id,
    a.guid,
    a.url,
    a.title,
    a.author,
    a.content,
    a.excerpt,
    a.image_url,
    a.published_at,
    a.created_at,
    a.is_read,
    a.is_starred,
    a.is_read_later,
    f.title AS feed_title,
    COALESCE(c.name, 'Uncategorized') AS category
FROM articles a
JOIN feeds f ON f.id = a.feed_id
LEFT JOIN categories c ON c.id = f.category_id
WHERE f.user_id = ? AND a.is_starred = 1
ORDER BY COALESCE(a.published_at, a.created_at) DESC, a.id DESC
LIMIT ? OFFSET ?
`

type ListStarredArticlesParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListStarredArticlesRow struct {
	ID          int64          `json:"id"`
	FeedID      int64          `json:"feed_id"`
	Guid        string         `json:"guid"`
	Url         string         `json:"url"`
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	Content     sql.NullString `json:"content"`
	Excerpt     sql.NullString `json:"excerpt"`
	ImageUrl    sql.NullString `json:"image_url"`
	PublishedAt sql.NullTime   `json:"published_at"`
	CreatedAt   time.Time      `json:"created_at"`
	IsRead      int64          `json:"is_read"`
	IsStarred   int64          `json:"is_starred"`
	IsReadLater int64          `json:"is_read_later"`
	FeedTitle   string         `json:"feed_title"`
	Category    string         `json:"category"`
}

func (q *Queries) ListStarredArticles(ctx context.Context, arg ListStarredArticlesParams) ([]ListStarredArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listStarredArticles, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStarredArticlesRow
	for rows.Next() {
		var i ListStarredArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Url,
			&i.Title,
			&i.Author,
			&i.Content,
			&i.Excerpt,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.IsReadLater,
			&i.FeedTitle,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadArticles = `-- name: ListUnreadArticles :many
SELECT
    a.id,
    a.feed_id,
    a.guid,
    a.url,
    a.title,
    a.author,
    a.content,
    a.excerpt,
    a.image_url,
    a.published_at,
    a.created_at,
    a.is_read,
    a.is_starred,
    a.is_read_later,
    f.title AS feed_title,
    COALESCE(c.name, 'Uncategorized') AS category
FROM articles a
JOIN feeds f ON f.id = a.feed_id
LEFT JOIN categories c ON c.id = f.category_id
WHERE f.user_id = ? AND a.is_read = 0
ORDER BY COALESCE(a.published_at, a.created_at) DESC, a.id DESC
LIMIT ? OFFSET ?
`

type ListUnreadArticlesParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListUnreadArticlesRow struct {
	ID          int64          `json:"id"`
	FeedID      int64          `json:"feed_id"`
	Guid        string         `json:"guid"`
	Url         string         `json:"url"`
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	Content     sql.NullString `json:"content"`
	Excerpt     sql.NullString `json:"excerpt"`
	ImageUrl    sql.NullString `json:"image_url"`
	PublishedAt sql.NullTime   `json:"published_at"`
	CreatedAt   time.Time      `json:"created_at"`
	IsRead      int64          `json:"is_read"`
	IsStarred   int64          `json:"is_starred"`
	IsReadLater int64          `json:"is_read_later"`
	FeedTitle   string         `json:"feed_title"`
	Category    string         `json:"category"`
}

func (q *Queries) ListUnreadArticles(ctx context.Context, arg ListUnreadArticlesParams) ([]ListUnreadArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadArticles, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnreadArticlesRow
	for rows.Next() {
		var i ListUnreadArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Url,
			&i.Title,
			&i.Author,
			&i.Content,
			&i.Excerpt,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.IsReadLater,
			&i.FeedTitle,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllArticlesRead = `-- name: MarkAllArticlesRead :exec
UPDATE articles
SET is_read = 1
WHERE feed_id IN (SELECT id FROM feeds WHERE user_id = ?)
`

func (q *Queries) MarkAllArticlesRead(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, markAllArticlesRead, userID)
	return err
}

const markArticleRead = `-- name: MarkArticleRead :exec
UPDATE articles
SET is_read = ?
WHERE articles.id = ?
  AND articles.feed_id IN (SELECT feeds.id FROM feeds WHERE feeds.user_id = ?)
`

type MarkArticleReadParams struct {
	IsRead int64 `json:"is_read"`
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) MarkArticleRead(ctx context.Context, arg MarkArticleReadParams) error {
	_, err := q.db.ExecContext(ctx, markArticleRead, arg.IsRead, arg.ID, arg.UserID)
	return err
}

const markCategoryArticlesRead = `-- name: MarkCategoryArticlesRead :exec
UPDATE articles
SET is_read = 1
WHERE feed_id IN (
    SELECT id FROM feeds WHERE user_id = ? AND category_id = ?
)
`

type MarkCategoryArticlesReadParams struct {
	UserID     int64         `json:"user_id"`
	CategoryID sql.NullInt64 `json:"category_id"`
}

func (q *Queries) MarkCategoryArticlesRead(ctx context.Context, arg MarkCategoryArticlesReadParams) error {
	_, err := q.db.ExecContext(ctx, markCategoryArticlesRead, arg.UserID, arg.CategoryID)
	return err
}

const markFeedArticlesRead = `-- name: MarkFeedArticlesRead :exec
UPDATE articles
SET is_read = 1
WHERE feed_id = ?
  AND feed_id IN (SELECT id FROM feeds WHERE user_id = ?)
`

type MarkFeedArticlesReadParams struct {
	FeedID int64 `json:"feed_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) MarkFeedArticlesRead(ctx context.Context, arg MarkFeedArticlesReadParams) error {
	_, err := q.db.ExecContext(ctx, markFeedArticlesRead, arg.FeedID, arg.UserID)
	return err
}

const searchArticles = `-- name: SearchArticles :many
SELECT
    a.id,
    a.feed_id,
    a.url,
    a.title,
    a.excerpt,
    a.image_url,
    a.published_at,
    f.title AS feed_title,
    snippet(fts, 0, '<mark>', '</mark>', '...', 12) AS title_snippet,
    snippet(fts, 1, '<mark>', '</mark>', '...', 36) AS content_snippet
FROM articles_fts fts
JOIN articles a ON a.id = fts.rowid
JOIN feeds f ON f.id = a.feed_id
WHERE fts.content MATCH ?
  AND f.user_id = ?
ORDER BY bm25(fts)
LIMIT 50
`

type SearchArticlesParams struct {
	Content string `json:"content"`
	UserID  int64  `json:"user_id"`
}

type SearchArticlesRow struct {
	ID             int64          `json:"id"`
	FeedID         int64          `json:"feed_id"`
	Url            string         `json:"url"`
	Title          string         `json:"title"`
	Excerpt        sql.NullString `json:"excerpt"`
	ImageUrl       sql.NullString `json:"image_url"`
	PublishedAt    sql.NullTime   `json:"published_at"`
	FeedTitle      string         `json:"feed_title"`
	TitleSnippet   string         `json:"title_snippet"`
	ContentSnippet string         `json:"content_snippet"`
}

func (q *Queries) SearchArticles(ctx context.Context, arg SearchArticlesParams) ([]SearchArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchArticles, arg.Content, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchArticlesRow
	for rows.Next() {
		var i SearchArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Url,
			&i.Title,
			&i.Excerpt,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FeedTitle,
			&i.TitleSnippet,
			&i.ContentSnippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setArticleReadLater = `-- name: SetArticleReadLater :exec
UPDATE articles
SET is_read_later = ?
WHERE articles.id = ?
  AND articles.feed_id IN (SELECT feeds.id FROM feeds WHERE feeds.user_id = ?)
`

type SetArticleReadLaterParams struct {
	IsReadLater int64 `json:"is_read_later"`
	ID          int64 `json:"id"`
	UserID      int64 `json:"user_id"`
}

func (q *Queries) SetArticleReadLater(ctx context.Context, arg SetArticleReadLaterParams) error {
	_, err := q.db.ExecContext(ctx, setArticleReadLater, arg.IsReadLater, arg.ID, arg.UserID)
	return err
}

const starArticle = `-- name: StarArticle :exec
UPDATE articles
SET is_starred = ?
WHERE articles.id = ?
  AND articles.feed_id IN (SELECT feeds.id FROM feeds WHERE feeds.user_id = ?)
`

type StarArticleParams struct {
	IsStarred int64 `json:"is_starred"`
	ID        int64 `json:"id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) StarArticle(ctx context.Context, arg StarArticleParams) error {
	_, err := q.db.ExecContext(ctx, starArticle, arg.IsStarred, arg.ID, arg.UserID)
	return err
}

const updateArticleFromFeed = `-- name: UpdateArticleFromFeed :exec
UPDATE articles
SET url = ?,
    title = ?,
    author = ?,
    content = ?,
    excerpt = ?,
    image_url = COALESCE(?, image_url),
    published_at = COALESCE(?, published_at)
WHERE feed_id = ?
  AND guid = ?
`

type UpdateArticleFromFeedParams struct {
	Url         string         `json:"url"`
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	Content     sql.NullString `json:"content"`
	Excerpt     sql.NullString `json:"excerpt"`
	ImageUrl    sql.NullString `json:"image_url"`
	PublishedAt sql.NullTime   `json:"published_at"`
	FeedID      int64          `json:"feed_id"`
	Guid        string         `json:"guid"`
}

func (q *Queries) UpdateArticleFromFeed(ctx context.Context, arg UpdateArticleFromFeedParams) error {
	_, err := q.db.ExecContext(ctx, updateArticleFromFeed,
		arg.Url,
		arg.Title,
		arg.Author,
		arg.Content,
		arg.Excerpt,
		arg.ImageUrl,
		arg.PublishedAt,
		arg.FeedID,
		arg.Guid,
	)
	return err
}
