// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boards.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const addArticleToBoard = `-- name: AddArticleToBoard :exec
INSERT OR IGNORE INTO board_articles (board_id, article_id)
SELECT ?1, ?2
WHERE EXISTS (SELECT 1 FROM boards b WHERE b.id = ?1 AND b.user_id = ?3)
  AND EXISTS (
      SELECT 1
      FROM articles a
      JOIN feeds f ON f.id = a.feed_id
      WHERE a.id = ?2 AND f.user_id = ?3
  )
`

type AddArticleToBoardParams struct {
	BoardID   int64 `json:"board_id"`
	ArticleID int64 `json:"article_id"`
	OwnerID   int64 `json:"owner_id"`
}

func (q *Queries) AddArticleToBoard(ctx context.Context, arg AddArticleToBoardParams) error {
	_, err := q.db.ExecContext(ctx, addArticleToBoard, arg.BoardID, arg.ArticleID, arg.OwnerID)
	return err
}

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (user_id, name, description)
VALUES (?, ?, ?)
ON CONFLICT(user_id, name) DO UPDATE SET description = excluded.description
RETURNING id, user_id, name, description, created_at
`

type CreateBoardParams struct {
	UserID      int64          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, createBoard, arg.UserID, arg.Name, arg.Description)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards
WHERE id = ? AND user_id = ?
`

type DeleteBoardParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteBoard(ctx context.Context, arg DeleteBoardParams) error {
	_, err := q.db.ExecContext(ctx, deleteBoard, arg.ID, arg.UserID)
	return err
}

const getBoard = `-- name: GetBoard :one
SELECT id, user_id, name, description, created_at
FROM boards
WHERE id = ? AND user_id = ?
`

type GetBoardParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetBoard(ctx context.Context, arg GetBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, getBoard, arg.ID, arg.UserID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listBoardArticles = `-- name: ListBoardArticles :many
SELECT
    a.id,
    a.feed_id,
    a.guid,
    a.url,
    a.title,
    a.author,
    a.content,
    a.excerpt,
    a.image_url,
    a.published_at,
    a.created_at,
    a.is_read,
    a.is_starred,
    a.is_read_later,
    f.title AS feed_title,
    COALESCE(c.name, 'Uncategorized') AS category
FROM board_articles ba
JOIN boards b ON b.id = ba.board_id
JOIN articles a ON a.id = ba.article_id
JOIN feeds f ON f.id = a.feed_id
LEFT JOIN categories c ON c.id = f.category_id
WHERE b.id = ? AND b.user_id = ?
ORDER BY ba.created_at DESC, a.id DESC
LIMIT ? OFFSET ?
`

type ListBoardArticlesParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListBoardArticlesRow struct {
	ID          int64          `json:"id"`
	FeedID      int64          `json:"feed_id"`
	Guid        string         `json:"guid"`
	Url         string         `json:"url"`
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	Content     sql.NullString `json:"content"`
	Excerpt     sql.NullString `json:"excerpt"`
	ImageUrl    sql.NullString `json:"image_url"`
	PublishedAt sql.NullTime   `json:"published_at"`
	CreatedAt   time.Time      `json:"created_at"`
	IsRead      int64          `json:"is_read"`
	IsStarred   int64          `json:"is_starred"`
	IsReadLater int64          `json:"is_read_later"`
	FeedTitle   string         `json:"feed_title"`
	Category    string         `json:"category"`
}

func (q *Queries) ListBoardArticles(ctx context.Context, arg ListBoardArticlesParams) ([]ListBoardArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listBoardArticles,
		arg.ID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBoardArticlesRow
	for rows.Next() {
		var i ListBoardArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Url,
			&i.Title,
			&i.Author,
			&i.Content,
			&i.Excerpt,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.IsReadLater,
			&i.FeedTitle,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoards = `-- name: ListBoards :many
SELECT
    b.id,
    b.user_id,
    b.name,
    b.description,
    b.created_at,
    COUNT(ba.article_id) AS article_count
FROM boards b
LEFT JOIN board_articles ba ON ba.board_id = b.id
WHERE b.user_id = ?
GROUP BY b.id
ORDER BY b.name
`

type ListBoardsRow struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	CreatedAt    time.Time      `json:"created_at"`
	ArticleCount int64          `json:"article_count"`
}

func (q *Queries) ListBoards(ctx context.Context, userID int64) ([]ListBoardsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBoards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBoardsRow
	for rows.Next() {
		var i ListBoardsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.ArticleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeArticleFromBoard = `-- name: RemoveArticleFromBoard :exec
DELETE FROM board_articles
WHERE board_id = ?
  AND article_id = ?
  AND board_id IN (SELECT id FROM boards WHERE user_id = ?)
`

type RemoveArticleFromBoardParams struct {
	BoardID   int64 `json:"board_id"`
	ArticleID int64 `json:"article_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) RemoveArticleFromBoard(ctx context.Context, arg RemoveArticleFromBoardParams) error {
	_, err := q.db.ExecContext(ctx, removeArticleFromBoard, arg.BoardID, arg.ArticleID, arg.UserID)
	return err
}
