// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (
    user_id, category_id, url, site_url, title, description, icon_url,
    fetch_interval_minutes
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, user_id, category_id, url, site_url, title, description, icon_url,
          etag, last_modified, last_fetched_at, last_error, error_count,
          fetch_interval_minutes, created_at
`

type CreateFeedParams struct {
	UserID               int64          `json:"user_id"`
	CategoryID           sql.NullInt64  `json:"category_id"`
	Url                  string         `json:"url"`
	SiteUrl              sql.NullString `json:"site_url"`
	Title                string         `json:"title"`
	Description          sql.NullString `json:"description"`
	IconUrl              sql.NullString `json:"icon_url"`
	FetchIntervalMinutes int64          `json:"fetch_interval_minutes"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.UserID,
		arg.CategoryID,
		arg.Url,
		arg.SiteUrl,
		arg.Title,
		arg.Description,
		arg.IconUrl,
		arg.FetchIntervalMinutes,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Url,
		&i.SiteUrl,
		&i.Title,
		&i.Description,
		&i.IconUrl,
		&i.Etag,
		&i.LastModified,
		&i.LastFetchedAt,
		&i.LastError,
		&i.ErrorCount,
		&i.FetchIntervalMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM feeds
WHERE id = ? AND user_id = ?
`

type DeleteFeedParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteFeed(ctx context.Context, arg DeleteFeedParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, arg.ID, arg.UserID)
	return err
}

const getFeed = `-- name: GetFeed :one
SELECT id, user_id, category_id, url, site_url, title, description, icon_url,
       etag, last_modified, last_fetched_at, last_error, error_count,
       fetch_interval_minutes, created_at
FROM feeds
WHERE id = ? AND user_id = ?
`

type GetFeedParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetFeed(ctx context.Context, arg GetFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, arg.ID, arg.UserID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Url,
		&i.SiteUrl,
		&i.Title,
		&i.Description,
		&i.IconUrl,
		&i.Etag,
		&i.LastModified,
		&i.LastFetchedAt,
		&i.LastError,
		&i.ErrorCount,
		&i.FetchIntervalMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, user_id, category_id, url, site_url, title, description, icon_url,
       etag, last_modified, last_fetched_at, last_error, error_count,
       fetch_interval_minutes, created_at
FROM feeds
WHERE user_id = ?
ORDER BY title
`

func (q *Queries) ListFeeds(ctx context.Context, userID int64) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Url,
			&i.SiteUrl,
			&i.Title,
			&i.Description,
			&i.IconUrl,
			&i.Etag,
			&i.LastModified,
			&i.LastFetchedAt,
			&i.LastError,
			&i.ErrorCount,
			&i.FetchIntervalMinutes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeed = `-- name: UpdateFeed :one
UPDATE feeds
SET category_id = ?,
    url = ?,
    site_url = ?,
    title = ?,
    description = ?,
    fetch_interval_minutes = ?
WHERE id = ? AND user_id = ?
RETURNING id, user_id, category_id, url, site_url, title, description, icon_url,
          etag, last_modified, last_fetched_at, last_error, error_count,
          fetch_interval_minutes, created_at
`

type UpdateFeedParams struct {
	CategoryID           sql.NullInt64  `json:"category_id"`
	Url                  string         `json:"url"`
	SiteUrl              sql.NullString `json:"site_url"`
	Title                string         `json:"title"`
	Description          sql.NullString `json:"description"`
	FetchIntervalMinutes int64          `json:"fetch_interval_minutes"`
	ID                   int64          `json:"id"`
	UserID               int64          `json:"user_id"`
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, updateFeed,
		arg.CategoryID,
		arg.Url,
		arg.SiteUrl,
		arg.Title,
		arg.Description,
		arg.FetchIntervalMinutes,
		arg.ID,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Url,
		&i.SiteUrl,
		&i.Title,
		&i.Description,
		&i.IconUrl,
		&i.Etag,
		&i.LastModified,
		&i.LastFetchedAt,
		&i.LastError,
		&i.ErrorCount,
		&i.FetchIntervalMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const updateFeedFetchError = `-- name: UpdateFeedFetchError :exec
UPDATE feeds
SET last_fetched_at = CURRENT_TIMESTAMP,
    last_error = ?,
    error_count = error_count + 1
WHERE id = ? AND user_id = ?
`

type UpdateFeedFetchErrorParams struct {
	LastError sql.NullString `json:"last_error"`
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
}

func (q *Queries) UpdateFeedFetchError(ctx context.Context, arg UpdateFeedFetchErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedFetchError, arg.LastError, arg.ID, arg.UserID)
	return err
}

const updateFeedFetchSuccess = `-- name: UpdateFeedFetchSuccess :exec
UPDATE feeds
SET title = ?,
    site_url = ?,
    description = ?,
    etag = ?,
    last_modified = ?,
    last_fetched_at = CURRENT_TIMESTAMP,
    last_error = NULL,
    error_count = 0
WHERE id = ? AND user_id = ?
`

type UpdateFeedFetchSuccessParams struct {
	Title        string         `json:"title"`
	SiteUrl      sql.NullString `json:"site_url"`
	Description  sql.NullString `json:"description"`
	Etag         sql.NullString `json:"etag"`
	LastModified sql.NullString `json:"last_modified"`
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
}

func (q *Queries) UpdateFeedFetchSuccess(ctx context.Context, arg UpdateFeedFetchSuccessParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedFetchSuccess,
		arg.Title,
		arg.SiteUrl,
		arg.Description,
		arg.Etag,
		arg.LastModified,
		arg.ID,
		arg.UserID,
	)
	return err
}
