// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: filter_rules.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createFilterRule = `-- name: CreateFilterRule :one
INSERT INTO filter_rules (user_id, feed_id, match_type, pattern, action)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, feed_id, match_type, pattern, action, created_at
`

type CreateFilterRuleParams struct {
	UserID    int64         `json:"user_id"`
	FeedID    sql.NullInt64 `json:"feed_id"`
	MatchType string        `json:"match_type"`
	Pattern   string        `json:"pattern"`
	Action    string        `json:"action"`
}

func (q *Queries) CreateFilterRule(ctx context.Context, arg CreateFilterRuleParams) (FilterRule, error) {
	row := q.db.QueryRowContext(ctx, createFilterRule,
		arg.UserID,
		arg.FeedID,
		arg.MatchType,
		arg.Pattern,
		arg.Action,
	)
	var i FilterRule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedID,
		&i.MatchType,
		&i.Pattern,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFilterRule = `-- name: DeleteFilterRule :exec
DELETE FROM filter_rules
WHERE id = ? AND user_id = ?
`

type DeleteFilterRuleParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteFilterRule(ctx context.Context, arg DeleteFilterRuleParams) error {
	_, err := q.db.ExecContext(ctx, deleteFilterRule, arg.ID, arg.UserID)
	return err
}

const listFilterRules = `-- name: ListFilterRules :many
SELECT id, user_id, feed_id, match_type, pattern, action, created_at
FROM filter_rules
WHERE user_id = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListFilterRules(ctx context.Context, userID int64) ([]FilterRule, error) {
	rows, err := q.db.QueryContext(ctx, listFilterRules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterRule
	for rows.Next() {
		var i FilterRule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedID,
			&i.MatchType,
			&i.Pattern,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFilterRule = `-- name: UpdateFilterRule :exec
UPDATE filter_rules
SET feed_id = ?, match_type = ?, pattern = ?, action = ?
WHERE id = ? AND user_id = ?
`

type UpdateFilterRuleParams struct {
	FeedID    sql.NullInt64 `json:"feed_id"`
	MatchType string        `json:"match_type"`
	Pattern   string        `json:"pattern"`
	Action    string        `json:"action"`
	ID        int64         `json:"id"`
	UserID    int64         `json:"user_id"`
}

func (q *Queries) UpdateFilterRule(ctx context.Context, arg UpdateFilterRuleParams) error {
	_, err := q.db.ExecContext(ctx, updateFilterRule,
		arg.FeedID,
		arg.MatchType,
		arg.Pattern,
		arg.Action,
		arg.ID,
		arg.UserID,
	)
	return err
}
