// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Article struct {
	ID          int64          `json:"id"`
	FeedID      int64          `json:"feed_id"`
	Guid        string         `json:"guid"`
	Url         string         `json:"url"`
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	Content     sql.NullString `json:"content"`
	Excerpt     sql.NullString `json:"excerpt"`
	PublishedAt sql.NullTime   `json:"published_at"`
	CreatedAt   time.Time      `json:"created_at"`
	IsRead      int64          `json:"is_read"`
	IsStarred   int64          `json:"is_starred"`
}

type ArticlesFt struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Author  string `json:"author"`
}

type Category struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Name      string    `json:"name"`
	SortOrder int64     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
}

type Feed struct {
	ID                   int64          `json:"id"`
	UserID               int64          `json:"user_id"`
	CategoryID           sql.NullInt64  `json:"category_id"`
	Url                  string         `json:"url"`
	SiteUrl              sql.NullString `json:"site_url"`
	Title                string         `json:"title"`
	Description          sql.NullString `json:"description"`
	IconUrl              sql.NullString `json:"icon_url"`
	Etag                 sql.NullString `json:"etag"`
	LastModified         sql.NullString `json:"last_modified"`
	LastFetchedAt        sql.NullTime   `json:"last_fetched_at"`
	LastError            sql.NullString `json:"last_error"`
	ErrorCount           int64          `json:"error_count"`
	FetchIntervalMinutes int64          `json:"fetch_interval_minutes"`
	CreatedAt            time.Time      `json:"created_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
