// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Article struct {
	ID          int64          `json:"id"`
	FeedID      int64          `json:"feed_id"`
	Guid        string         `json:"guid"`
	Url         string         `json:"url"`
	Title       string         `json:"title"`
	Author      sql.NullString `json:"author"`
	Content     sql.NullString `json:"content"`
	Excerpt     sql.NullString `json:"excerpt"`
	PublishedAt sql.NullTime   `json:"published_at"`
	CreatedAt   time.Time      `json:"created_at"`
	IsRead      int64          `json:"is_read"`
	IsStarred   int64          `json:"is_starred"`
	ImageUrl    sql.NullString `json:"image_url"`
	IsReadLater int64          `json:"is_read_later"`
}

type ArticlesFt struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Author  string `json:"author"`
}

type Board struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type BoardArticle struct {
	BoardID   int64     `json:"board_id"`
	ArticleID int64     `json:"article_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Category struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Name      string    `json:"name"`
	SortOrder int64     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
}

type Feed struct {
	ID                   int64          `json:"id"`
	UserID               int64          `json:"user_id"`
	CategoryID           sql.NullInt64  `json:"category_id"`
	Url                  string         `json:"url"`
	SiteUrl              sql.NullString `json:"site_url"`
	Title                string         `json:"title"`
	Description          sql.NullString `json:"description"`
	IconUrl              sql.NullString `json:"icon_url"`
	Etag                 sql.NullString `json:"etag"`
	LastModified         sql.NullString `json:"last_modified"`
	LastFetchedAt        sql.NullTime   `json:"last_fetched_at"`
	LastError            sql.NullString `json:"last_error"`
	ErrorCount           int64          `json:"error_count"`
	FetchIntervalMinutes int64          `json:"fetch_interval_minutes"`
	CreatedAt            time.Time      `json:"created_at"`
}

type FilterRule struct {
	ID        int64         `json:"id"`
	UserID    int64         `json:"user_id"`
	FeedID    sql.NullInt64 `json:"feed_id"`
	MatchType string        `json:"match_type"`
	Pattern   string        `json:"pattern"`
	Action    string        `json:"action"`
	CreatedAt time.Time     `json:"created_at"`
}

type ReaderSetting struct {
	UserID                      int64     `json:"user_id"`
	DefaultFetchIntervalMinutes int64     `json:"default_fetch_interval_minutes"`
	RetentionDays               int64     `json:"retention_days"`
	Theme                       string    `json:"theme"`
	Density                     string    `json:"density"`
	RespectCacheHeaders         int64     `json:"respect_cache_headers"`
	UpdatedAt                   time.Time `json:"updated_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
