// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountUnreadArticles(ctx context.Context, userID int64) (int64, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFeed(ctx context.Context, arg DeleteFeedParams) error
	GetFeed(ctx context.Context, arg GetFeedParams) (Feed, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListArticlesByFeed(ctx context.Context, arg ListArticlesByFeedParams) ([]Article, error)
	ListCategories(ctx context.Context, userID int64) ([]Category, error)
	ListFeeds(ctx context.Context, userID int64) ([]Feed, error)
	ListRecentArticles(ctx context.Context, arg ListRecentArticlesParams) ([]ListRecentArticlesRow, error)
	MarkArticleRead(ctx context.Context, arg MarkArticleReadParams) error
	SearchArticles(ctx context.Context, arg SearchArticlesParams) ([]SearchArticlesRow, error)
	StarArticle(ctx context.Context, arg StarArticleParams) error
	UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error)
	UpdateFeedFetchError(ctx context.Context, arg UpdateFeedFetchErrorParams) error
	UpdateFeedFetchSuccess(ctx context.Context, arg UpdateFeedFetchSuccessParams) error
}

var _ Querier = (*Queries)(nil)
