// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlc

import (
	"context"
)

const getReaderSettings = `-- name: GetReaderSettings :one
SELECT user_id, default_fetch_interval_minutes, retention_days, theme, density,
       respect_cache_headers, updated_at
FROM reader_settings
WHERE user_id = ?
`

func (q *Queries) GetReaderSettings(ctx context.Context, userID int64) (ReaderSetting, error) {
	row := q.db.QueryRowContext(ctx, getReaderSettings, userID)
	var i ReaderSetting
	err := row.Scan(
		&i.UserID,
		&i.DefaultFetchIntervalMinutes,
		&i.RetentionDays,
		&i.Theme,
		&i.Density,
		&i.RespectCacheHeaders,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertReaderSettings = `-- name: UpsertReaderSettings :one
INSERT INTO reader_settings (
    user_id, default_fetch_interval_minutes, retention_days, theme, density,
    respect_cache_headers
) VALUES (
    ?, ?, ?, ?, ?, ?
)
ON CONFLICT(user_id) DO UPDATE SET
    default_fetch_interval_minutes = excluded.default_fetch_interval_minutes,
    retention_days = excluded.retention_days,
    theme = excluded.theme,
    density = excluded.density,
    respect_cache_headers = excluded.respect_cache_headers,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, default_fetch_interval_minutes, retention_days, theme, density,
          respect_cache_headers, updated_at
`

type UpsertReaderSettingsParams struct {
	UserID                      int64  `json:"user_id"`
	DefaultFetchIntervalMinutes int64  `json:"default_fetch_interval_minutes"`
	RetentionDays               int64  `json:"retention_days"`
	Theme                       string `json:"theme"`
	Density                     string `json:"density"`
	RespectCacheHeaders         int64  `json:"respect_cache_headers"`
}

func (q *Queries) UpsertReaderSettings(ctx context.Context, arg UpsertReaderSettingsParams) (ReaderSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertReaderSettings,
		arg.UserID,
		arg.DefaultFetchIntervalMinutes,
		arg.RetentionDays,
		arg.Theme,
		arg.Density,
		arg.RespectCacheHeaders,
	)
	var i ReaderSetting
	err := row.Scan(
		&i.UserID,
		&i.DefaultFetchIntervalMinutes,
		&i.RetentionDays,
		&i.Theme,
		&i.Density,
		&i.RespectCacheHeaders,
		&i.UpdatedAt,
	)
	return i, err
}
